force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Fligh Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/PrefferedTripStart__c.field-meta.xml
<CustomField>
    <fullName>PrefferedTripStart__c</fullName>
    <label>Preffered Trip Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flight search</fullName>
            </value>
            <value>
                <fullName>Flight booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/flight/FlightSelectorController.cls
public with sharing class FlightSelectorController {
    @AuraEnabled
    public static  List<FlightWrapper> getFlightsWithUnbookedTickets(String recordId) {
        Trip__c trip = [
                SELECT Id, Contact__c, PrefferedTripStart__c 
                FROM Trip__c 
                WHERE Id =:recordId 
                LIMIT 1
            ];

            List<FlightWrapper> avalibaleFlights = new List<FlightWrapper>();

        for(Ticket__c ticket : [SELECT Id, Flight__c, Flight__r.Name FROM Ticket__c  WHERE Contact__c = '' AND DAY_ONLY(Flight__r.Start__c) = :trip.PrefferedTripStart__c]) {
            avalibaleFlights.add(new FlightWrapper(ticket.Flight__r.Name, ticket.Flight__c));
        }

        return avalibaleFlights;
    }

    @AuraEnabled
    public static void assignFlightOnTrip(String tripdId, String flightId) {
        Trip__c trip = [
                SELECT Id, Contact__c, Flight__c 
                FROM Trip__c 
                WHERE Id =:tripdId 
                LIMIT 1
            ];

        Ticket__c ticket = [
                SELECT Id, Flight__c 
                FROM Ticket__c 
                WHERE Contact__c = '' 
                AND Flight__c = :flightId
            ];

        ticket.Contact__c = trip?.Contact__c;
        trip.Flight__c = ticket?.Flight__c;
        trip.Status__c = Constants.TRIP_STATUS_FLIGHT_BOOKED;
        

        List<SObject> objectsToUpdate = new List<SObject>();
        objectsToUpdate.add(trip);
        objectsToUpdate.add(ticket);

        update objectsToUpdate;
    }

    @AuraEnabled
    public static void cancelFlight(String tripdId, String flightId) {
        Trip__c trip = [
                SELECT Id, Contact__c, Flight__c,Status__c
                FROM Trip__c 
                WHERE Id =:tripdId 
                LIMIT 1
            ];

        Ticket__c ticket = [
                SELECT Id, Flight__c,Contact__c
                FROM Ticket__c 
                WHERE Contact__c = :trip.Contact__c
                AND Flight__c = :flightId
            ];

        ticket.Contact__c = null;
        trip.Flight__c = null;
        trip.Status__c = Constants.TRIP_STATUS_FLIGHT_SEARCH;

        List<SObject> objectsToUpdate = new List<SObject>();
        objectsToUpdate.add(trip);
        objectsToUpdate.add(ticket);

        update objectsToUpdate;
    }
}