force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Fligh Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/fields/PrefferedTripStart__c.field-meta.xml
<CustomField>
    <fullName>PrefferedTripStart__c</fullName>
    <label>Preffered Trip Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/flight/FlightSelectorController_Test.cls
@IsTest
public with sharing class FlightSelectorController_Test {
    @IsTest
    private static void getFlightsWithUnbookedTickets_Test() {
        DataFactory factory = new DataFactory();
        Integer ticketsCount = 3;
        Contact testContact = factory.createContact(true);

        Trip__c testTrip = factory.createTrip(false);
        testTrip.Contact__c = testContact.Id;
        testTrip.PrefferedTripStart__c = Date.today();
        insert testTrip;

        Flight__c testFlight = factory.createFlight(false);
        testFlight.Start__c = Date.today();
        insert testFlight;

        List<Ticket__c> testTickets = new List<Ticket__c>();
        for(Integer i = 0; i < ticketsCount; i++) {
            Ticket__c testTicket = factory.createTicket(false);
            testTicket.Flight__c = testFlight.Id;
            testTickets.add(testTicket);
        }

        insert testTickets;

        Test.startTest();
        List<FlightWrapper> flightToTest = FlightSelectorController.getFlightsWithUnbookedTickets(testTrip.Id);
        Test.stopTest();

        System.assert(flightToTest.size()>0, 'Flights not found');

    }
}